spring:
  datasource:
    url: jdbc:mysql://${{ MYSQLUSER }}:${{ MYSQLPASSWORD }}@${{ MYSQLHOST }}:${{ MYSQLPORT }}/${{ MYSQLDEFAULTDATABASE }}
    username: ${{ MYSQLUSER }}
    password: ${{ MYSQLPASSWORD }}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
