spring:
  datasource:
    url: jdbc:mysql://${{ PROD_DB_NAME }}:${{ PROD_DB_PASSWORD }}@${{ PROD_DB_HOST }}:${{ PROD_DB_PORT }}/${{ PROD_DB_NAME }}
    username: ${{ PROD_DB_NAME }}
    password: ${{ PROD_DB_PASSWORD }}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
